### ISSUE TITLE
manifest.json should be at the root of the repository

### ISSUE THREAD

**Issue by argenos** [hungsu/obsidian-prompt#6]
This commit 59761e13627cebe06a460b9aad70c25b6191193a introduces changes that don't enable the community store nor the hub to fetch data from this plugin: 
![image](https://user-images.githubusercontent.com/5426039/139699113-f192f748-98ed-41a9-a369-870cf3a175a0.png)

For more information see: https://marcus.se.net/obsidian-plugin-docs/publishing/submit-your-plugin and the [hub guide for submitting plugins](https://publish.obsidian.md/hub/04+-+Guides%2C+Workflows%2C+%26+Courses/Guides/How+to+add+your+plugin+to+the+community+plugin+list)

**Comment by hungsu** [comment]
Thanks so much for flagging this! This is now fixed! :)
