### ISSUE TITLE
FR: Add option to change time-out of a pop-up.

### ISSUE THREAD

**Issue by gala8y** [hungsu/obsidian-prompt#8]
Hi, thanks for developing this! I really like the idea very much.
I'm not sure if this is possible, but it would be great to have ability to change time-out of prompts.
Not a problem for this to affect all Obsidian prompts.
Best!

**Comment by hungsu** [comment]
Glad you like the plugin! I'll see what I can do :)

**Comment by gala8y** [comment]
Thanks a lot. I am really gonna use Prompts. It is positively simple (I mean functionally, not coding) implementation of an idea I had for a long time - to prepare such a list of prompts and gently go through them in some obstructive manner. I am curious how it's gonna work.

**Comment by karl6211** [comment]
Hi Hunsu,
Thank you so much for this plugin! I'll second the previous request about having the option to choose how long the prompt stays up. Some prompts are long to read but they disappear before I can finish. Not sure if you can change this at the plugin level or the whole Obsidian settings, but you can, that would be great appreciated. Thanks again!

**Comment by karl6211** [comment]
Much appreciated, Hunsu. I do indeed like to use it. I'm a fiction writer
and what I like to do is get random sentence prompts for inspiration as I'm
writing my own prose. The problem is that sometimes the sentence is long,
so there's not enough time to read it before it times out.

Cheers,
Karl

**Comment by hungsu** [comment]
@karl6211 @gala8y so sorry this has taken so long - the latest release of Prompt has a little slider to allow you to choose how long to keep the prompt on screen! Please let me know if you have any more suggestions

![Obsidian_A04FyPjrdy](https://user-images.githubusercontent.com/1990680/230755540-7106b59a-bc54-4cd1-9aa6-9a54f90ab8e8.jpg)

**Comment by gala8y** [comment]
@hungsu thank you very much for adding this! i will come back with some ideas, if i have anything of value, but i really think simplicity here is cool (i mean over all UX/design of the plugin).

@karl6211 interesting use case. i use it to kind of remind myself of meta frames, to keep some context in mind.

**Comment by karl6211** [comment]
Thank you so much @hungsu for following up! Much appreciated.
